> init
<<<
+ file1.txt wug.txt
> add file1.txt
<<<
+ file2.txt wug.txt
> add file2.txt
<<<
+ file3.txt wug.txt
> add file3.txt
<<<
+ file3-1.txt wug.txt
> add file3-1.txt
<<<
+ file6.txt wug.txt
> add file6.txt
<<<
+ file7.txt wug.txt
> add file7.txt
<<<
+ file8-1.txt wug.txt
> add file8-1.txt
<<<
+ file8-2.txt wug.txt
> add file8-2.txt
<<<
+ file8-3.txt wug.txt
> add file8-3.txt
<<<
> commit "setup files"
<<<
> branch other-branch
<<<
